#Functionality

# Enables mouse usage within tmux
set -g mouse on

# Enables key usage as in vi
setw -g mode-keys vi



#Style

#Status position to the top
set -g status-position top

#Longer Status name
set -g status-left-length 100

#Colors
